

name: CI

on:

  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  
  fmt:
    
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: hashicorp/setup-terraform@v2

    - name: Terraform fmt
      id: fmt
      run: terraform fmt
      
    - name: commit
      run: |
          git config --local user.email "action@github.com"
          git config --local user.name "Deploy Action"
          git commit -am "change image tag"
   
    - name: push
      uses: ad-m/github-push-action@master
      
  
  tfsec:
    name: tfsec
    runs-on: ubuntu-latest
    needs: fmt
    steps:
      - name: Teste
        uses: actions/checkout@master
      - name: tfsec
        uses: aquasecurity/tfsec-action@v1.0.0
        
        
        
