

name: CI

on:

  push:
    paths:
      - "**.tf"

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: hashicorp/setup-terraform@v2

    - name: Terraform fmt
      id: fmt
      run: terraform fmt 
      continue-on-error: true
                
    #- name: commit
    #  run: |
    #    git config --local user.email "action@github.com"
    #    git config --local user.name "Deploy Action"
    #    git commit -am "change image tag"
    #- name: push
    #  uses: ad-m/github-push-action@master
      
